---
title: "Data Science from Scratch"
draft: false
showMeta:       false
showActions:    false
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(dplyr)
library(kableExtra)
library(stringr)

check_box <- '<input type="checkbox" checked onclick="return false;">'

uncheck_box <- '<input type="checkbox" unchecked onclick="return false;">'

build_link <- function(url, Topic) {
  as.character(str_glue("<a href={url}>{Topic}</a>"))
}
```

<br>

# Programming and Computer Science

```{r}
prog_groups <- c(rep("First Steps", 5), rep("Algorithms", 1),
                 rep("Essential Tasks", 5))

prog_topics <- c("Variable Assignment",
                 "Data Types",
                 "Logic",
                 "Collections",
                 "Loops",
                 "Bubble Sort",
                 "Length of Values",
                 "Unique Values",
                 "Maximum",
                 "Minimum",
                 "Sum")

tibble(` ` = prog_groups, Topic = prog_topics) %>% 
  mutate(R = case_when(
    Topic == "Variable Assignment" ~ check_box,
    Topic == "Data Types" ~ uncheck_box,
    Topic == "Logic" ~ uncheck_box,
    Topic == "Collections" ~ uncheck_box,
    Topic == "Loops" ~ uncheck_box,
    Topic == "Bubble Sort" ~ check_box,
    Topic == "Length of Values" ~ check_box,
    Topic == "Unique Values" ~ check_box,
    Topic == "Maximum" ~ check_box,
    Topic == "Minimum" ~ check_box,
    Topic == "Sum" ~ check_box
    )) %>% 
  mutate(Python = case_when(
    Topic == "Variable Assignment" ~ check_box,
    Topic == "Data Types" ~ uncheck_box,
    Topic == "Logic" ~ uncheck_box,
    Topic == "Collections" ~ uncheck_box,
    Topic == "Loops" ~ uncheck_box,
    Topic == "Bubble Sort" ~ check_box,
    Topic == "Length of Values" ~ check_box,
    Topic == "Unique Values" ~ check_box,
    Topic == "Maximum" ~ check_box,
    Topic == "Minimum" ~ check_box,
    Topic == "Sum" ~ check_box
  )) %>% 
  mutate(Topic = case_when(
    Topic == "Variable Assignment" ~ 
      build_link("/2018/07/variable-assignment/", Topic),
    Topic == "Bubble Sort" ~ build_link("/2018/07/bubble-sort/", Topic),
    Topic == "Length of Values" ~ build_link("/2018/07/central-tendency/#length", Topic),
    Topic == "Unique Values" ~ build_link("/2018/07/central-tendency/#unique-values", Topic),
    Topic == "Maximum" ~ build_link("/2018/07/central-tendency/#max", Topic),
    Topic == "Minimum" ~ build_link("/2018/07/central-tendency/#min", Topic),
    Topic == "Sum" ~ build_link("/2018/07/central-tendency/#sum", Topic),
    TRUE ~ Topic
    )) %>% 
  kable(escape = FALSE, align = "c") %>% 
  kable_styling(bootstrap_options = c("hover", "responsive")) %>% 
  column_spec(1, bold = TRUE) %>% 
  collapse_rows(columns = 1, valign = "top")
```

<br>

# Statistics

```{r}
stat_groups <- c(rep("Central Tendency", 3),
                 rep("Dispersion", 2),
                 rep("Correlation", 2),
                 rep("Linear Models", 2),
                 rep("Generalized Linear Models", 3))

stat_topics <- c("Mean", "Median", "Mode",
                 "Standard Deviation", 
                 "Variance",
                 "Pearson's",
                 "Spearman's",
                 "Simple Linear Regression", 
                 "Linear Regression",
                 "Binomial",
                 "Gaussian",
                 "Poisson")

tibble(` ` = stat_groups, Topic = stat_topics) %>% 
  mutate(R = case_when(
    Topic == "Mean" ~ check_box,
    Topic == "Mode" ~ check_box,
    Topic == "Median" ~ check_box,
    TRUE ~ uncheck_box
    )) %>% 
  mutate(Python = case_when(
    Topic == "Mean" ~ check_box,
    Topic == "Mode" ~ check_box,
    Topic == "Median" ~ check_box,
    TRUE ~ uncheck_box
    )) %>% 
  mutate(Topic = case_when(
    Topic == "Mean" ~ build_link("/2018/07/central-tendency/#mean", Topic),
    Topic == "Mode" ~ build_link("/2018/07/central-tendency/#mode", Topic),
    Topic == "Median" ~ build_link("/2018/07/central-tendency/#median", Topic),
    TRUE ~ Topic
    )) %>% 
  kable(escape = FALSE, align = "c") %>%
  kable_styling() %>% 
  column_spec(1, bold = TRUE) %>% 
  collapse_rows(columns = 1, valign = "top")
```

# Graphs

```{r}
graph_groups <- c(rep("Representations", 4),
                  rep("Higher Dimensions", 2),
                  "Algorithms")

graph_topics <- c("Adjacency Matrix",
                  "Adjacency List",
                  "Edge List",
                  "Incidence Matrix",
                  "Multipartite Graphs",
                  "Multiplex Graphs",
                  "Shortest Path")

tibble(` ` = graph_groups, Topic = graph_topics) %>% 
  mutate(R = uncheck_box) %>% 
  mutate(Python = uncheck_box) %>% 
  # mutate(`C++` = uncheck_box) %>% 
  # mutate(Rcpp = uncheck_box) %>% 
  # mutate(Details = stat_details) %>% 
  kable(escape = FALSE, align = "c") %>%
  kable_styling() %>% 
  column_spec(1, bold = TRUE) %>% 
  collapse_rows(columns = 1, valign = "top")
```

# Unsupervised Learning

```{r}
unsup_groups <- c(rep("Clustering", 2),
                  "Dimensionality Reduction")

unsup_topics <- c("k-means", 
                  "Principal Component Analysis", 
                  "Factor Analysis")

tibble(` ` = unsup_groups, Topic = unsup_topics) %>% 
  mutate(R = uncheck_box) %>% 
  mutate(Python = uncheck_box) %>% 
  # mutate(`C++` = uncheck_box) %>% 
  # mutate(Rcpp = uncheck_box) %>% 
  # mutate(Details = stat_details) %>% 
  kable(escape = FALSE, align = "c") %>%
  kable_styling() %>% 
  column_spec(1, bold = TRUE) %>% 
  collapse_rows(columns = 1, valign = "top")
```


# Supervised Learning

```{r}
sup_groups <- c(rep("Classification", 4),
                rep("Regression", 2))

sup_topics <- c("Naive Bayes", 
                "k-Nearest Neighbors", 
                "Support Vector Machine",
                "Random Forests",
                "Support Vector Machine",
                "Random Forests")

tibble(` ` = sup_groups, Topic = sup_topics) %>% 
  mutate(R = uncheck_box) %>% 
  mutate(Python = uncheck_box) %>% 
  # mutate(`C++` = uncheck_box) %>% 
  # mutate(Rcpp = uncheck_box) %>% 
  # mutate(Details = stat_details) %>% 
  kable(escape = FALSE, align = "c") %>%
  kable_styling() %>% 
  column_spec(1, bold = TRUE) %>% 
  collapse_rows(columns = 1, valign = "top")
```



