---
title: Programming Essentials - Variables
author: Brendan Knapp
date: '2018-07-02'
slug: programming-essentials-variables
categories:
  - data-science-from-scratch
tags: []
# thumbnailImage: 
metaAlignment: center
coverMeta: out
summary: A brief look at some essential programming concepts in R, Python, and C++/Rcpp.
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.width = 11, fig.height = 8, fig.align = "center",
                      message = FALSE, warning = FALSE)
```

```{r echo=FALSE}
# library(reticulate)
# library(Rcpp)
```

# Variables

## R

```{r}
var_R <- 1

var_R
```

## Python

```{r}
var_PY <- 1

print(var_PY)
```


## C++

```{Rcpp, ref.label=knitr::all_rcpp_labels(), include=FALSE}
```

### Pure C++

```{Rcpp, eval=FALSE}
#include <iostream>

int main() {
  int x_CPP = 1;

  std::cout << x_CPP;
  
  return 0;
}
```

```{r echo=FALSE}
# cd content/post/cpp & 
#   g++ -c programming_essentials1.cpp &
#   g++ -o programming_essentials1.exe programming_essentials1.o & 
#   cpp/programming_essentials1.exe
# system("cd content/post/cpp")
# system("g++ -c code-variables1.cpp")
# system("g++ -o code-variables1.exe code-variables1.o")
system("cpp/code-variables1.exe")
```

### Rcpp

```{Rcpp, eval=TRUE}
#include <Rcpp.h>       // R to C++ to R interface
// [[Rcpp::export]]

int RCPP_function() {
  int x_RCPP = 1;
  
  return x_RCPP;
}
```

```{r}
RCPP_function() # now accessible from R
```


